"""Build visual/preview.html — the whole ceremony in one file, no server.

For review only. It bakes today's oracle.json and sky_state.json into the page
and shims fetch() so /oracle.json and /natal resolve locally: the sky is frozen
at build time, and natal positions come from low-precision series (sun ~0.01deg,
moon ~0.3deg) instead of Swiss Ephemeris.

Everything the reviewer actually judges — corpus, selection, pacing, the shape
of the ceremony — is the real code, untouched. pIdx below mirrors librarian._idx
bit for bit (asserted against Python over a seed range), so a given
(planet, aspect, target, variant) composes the SAME sentence here as on the
machine.

Known and inherent: the ~0.3deg moon approximation shifts some orbs, which can
reorder the transit list. Since the variant is seed+index, a reordered transit
draws a different verb and note from the same pool — measured at 10 of 14
sentences identical to the live server across three dates, the rest differing by
position rather than by selection. Fixing that would mean shipping Swiss
Ephemeris to the browser, which is the thing this file exists to avoid.

Regenerate with:

    python3 tools/build_preview.py

Do NOT install this on the machine. run.sh serves the real thing.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import librarian as L                                       # noqa: E402

tv = (ROOT / "visual" / "tv.html").read_text(encoding="utf-8")
oracle = json.loads((ROOT / "visual" / "oracle.json").read_text(encoding="utf-8"))
sky = json.loads((ROOT / "sky_state.json").read_text(encoding="utf-8"))

# Only the pieces compose_transit() needs. Baked from librarian.py at build
# time rather than retyped, so the preview cannot drift from the corpus.
LIB = {
    "desks": L.PLANET_DESK,
    "verbs_one": {m: v["verbs_one"] for m, v in L.ASPECT_MODES.items()},
    "notes": L.TRANSIT_NOTES,
}

built = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

shim = """
<script>
/* ==========================================================================
   PREVIEW SHIM — not part of the installation. Generated by
   tools/build_preview.py. Serves a frozen sky and computes natal positions
   in-page so the ceremony runs from a file:// URL with nothing installed.
   ========================================================================== */
const PREVIEW = {
  oracle: __ORACLE__,
  sky: __SKY__,
  lib: __LIB__,
  built: "__BUILT__"
};

const P_SIGNS = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra",
  "Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const P_ASPECTS = [["Conjunction",0,8],["Opposition",180,8],["Trine",120,7],
  ["Square",90,6],["Sextile",60,5]];

const rad = d => d * Math.PI / 180;
function julday(y, m, d, h){
  if (m <= 2){ y -= 1; m += 12; }
  const A = Math.floor(y / 100), B = 2 - A + Math.floor(A / 4);
  return Math.floor(365.25 * (y + 4716)) + Math.floor(30.6001 * (m + 1))
       + d + B - 1524.5 + h / 24;
}
// Meeus, low precision. Sun ~0.01 deg, moon ~0.3 deg — well inside every orb
// in the table above, which is what the reading actually depends on.
function sunLon(n){
  const L = 280.460 + 0.9856474 * n, g = rad(357.528 + 0.9856003 * n);
  return ((L + 1.915 * Math.sin(g) + 0.020 * Math.sin(2 * g)) % 360 + 360) % 360;
}
function moonLon(n){
  const Lp = 218.316 + 13.176396 * n,
        M  = rad(134.963 + 13.064993 * n),
        F  = rad(93.272 + 13.229350 * n),
        D  = rad(297.850 + 12.190749 * n),
        Ms = rad(357.529 + 0.985600 * n);
  const l = Lp + 6.289 * Math.sin(M) - 1.274 * Math.sin(2 * D - M)
          + 0.658 * Math.sin(2 * D) + 0.214 * Math.sin(2 * M)
          - 0.186 * Math.sin(Ms) - 0.114 * Math.sin(2 * F);
  return ((l % 360) + 360) % 360;
}
// mirrors librarian._idx / _pick exactly. NOT the old (seed*31 + salt*7) form:
// that was replaced by a salted hash, and a preview that kept the arithmetic
// would quietly show different lines from the machine it is previewing.
function pIdx(seed, salt, n){
  if (n <= 0) return 0;
  let h = (Math.imul(seed & 0x7fffffff, 2654435761) ^ Math.imul(salt + 1, 2246822519)) >>> 0;
  h = (h ^ (h >>> 15)) >>> 0;
  h = Math.imul(h, 2246822507) >>> 0;
  h = (h ^ (h >>> 13)) >>> 0;
  return h % n;
}
const pPick = (pool, v, salt) => pool[pIdx(v, salt, pool.length)];

function previewNatal(d, m, y){
  const n = julday(y, m, d, 12.0) - 2451545.0;
  const sun = sunLon(n), moon = moonLon(n);
  const seed = y * 372 + m * 31 + d;
  const hits = [];
  for (const [name, info] of Object.entries(PREVIEW.sky.planets || {})){
    const si = P_SIGNS.indexOf(info.sign);
    if (si < 0) continue;
    const lon = si * 30 + info.degree;
    for (const [target, tlon] of [["Sun", sun], ["Moon", moon]]){
      let dd = Math.abs(lon - tlon) % 360;
      if (dd > 180) dd = 360 - dd;
      for (const [asp, angle, orb] of P_ASPECTS){
        const off = Math.abs(dd - angle);
        if (off <= orb){ hits.push([off, name, asp, target]); break; }
      }
    }
  }
  hits.sort((a, b) => a[0] - b[0]);
  const seen = new Set(), picked = [];
  for (const h of hits){
    const k = h[1] + h[2];
    if (seen.has(k)) continue;
    seen.add(k); picked.push(h);
    if (picked.length === 6) break;
  }
  const transits = picked.map(([off, name, asp, target], i) => {
    const desk = PREVIEW.lib.desks[name] || name;
    const verbs = (PREVIEW.lib.verbs_one[asp] || []);
    const notes = (PREVIEW.lib.notes[asp] || []);
    const v = seed + i;
    return {
      planet: name, type: asp, target, orb: +off.toFixed(2),
      approx: target === "Moon",
      line: desk.charAt(0).toUpperCase() + desk.slice(1) + " " +
            (verbs.length ? pPick(verbs, v, 3) : "is aspecting") + " your natal " + target + ".",
      note: notes.length ? pPick(notes, v, 6) : "",
    };
  });
  return {
    sun_sign: P_SIGNS[Math.floor(sun / 30)], sun_deg: +(sun % 30).toFixed(2),
    moon_sign: P_SIGNS[Math.floor(moon / 30)], moon_deg: +(moon % 30).toFixed(2),
    moon_confidence: "approximate (noon UT assumed)",
    transits,
  };
}

const _realFetch = window.fetch.bind(window);
window.fetch = async (url, opts) => {
  const u = String(url);
  const ok = body => new Response(JSON.stringify(body),
    { status: 200, headers: { "Content-Type": "application/json" } });
  if (u.includes("oracle.json")) return ok(PREVIEW.oracle);
  if (u.includes("/natal")){
    const q = new URLSearchParams(u.split("?")[1] || "");
    return ok(previewNatal(+q.get("d"), +q.get("m"), +q.get("y")));
  }
  return _realFetch(url, opts);
};

addEventListener("DOMContentLoaded", () => {
  // signalStatus() shows SIGNAL LOST for any file:// URL, on the assumption
  // that a file:// page cannot reach the sky. Here it can — the sky is baked
  // in — so suppress the banner once the oracle has loaded.
  setInterval(() => {
    const el = document.getElementById("signal-lost");
    if (el && typeof oracle !== "undefined" && oracle) el.style.display = "none";
  }, 400);

  const b = document.createElement("div");
  b.textContent = "PREVIEW - SKY FROZEN " + PREVIEW.built;
  b.style.cssText = "position:fixed;bottom:6px;right:10px;z-index:99;" +
    "font:10px/1 ui-monospace,Menlo,monospace;letter-spacing:.16em;" +
    "color:#6d6b67;opacity:.55;pointer-events:none;";
  document.body.appendChild(b);
});
</script>
"""

shim = (shim.replace("__ORACLE__", json.dumps(oracle, ensure_ascii=False))
            .replace("__SKY__", json.dumps({"planets": sky.get("planets", {})}, ensure_ascii=False))
            .replace("__LIB__", json.dumps(LIB, ensure_ascii=False))
            .replace("__BUILT__", built))

marker = "<script>"
i = tv.index(marker)
out = tv[:i] + shim + "\n" + tv[i:]
out = out.replace("<title>", "<title>PREVIEW · ", 1)

dest = ROOT / "visual" / "preview.html"
dest.write_text(out, encoding="utf-8")
print(f"wrote {dest}  ({len(out) // 1024} KB)  sky frozen {built}")
